name: Spring Boot PLayground

on:
  push:
    branches:
      - development

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: axel-op/googlejavaformat-action@v2.0.0